export const careerData = [

  { position: "Java Developer", 
    companyName: "Infosys", 
    description: "Required 2 years of experience", 
    applyLink: "https://www.naukri.com/", 
  }, 
  { position: "Android Developer", 
    companyName: "Zomato", 
    description: "Required MIN 4 years of experience", 
    applyLink: "https://www.naukri.com/",
  }, 
  { position: "Data Analyst", 
    companyName: "Walmart", 
    description: "Required 5 years of experience", 
    applyLink: "https://www.naukri.com/", 
  }, 
  { position: "Software Development Engineer in Testing", 
    companyName: "Persistent", 
    description: "Freshers are most welcomed", 
    applyLink: "https://www.naukri.com/", 
  }, 
  { position: "Full Web Devloper", 
    companyName: "TCS", 
    description: "Required 2 years of experience", 
    applyLink: "https://www.naukri.com/", 
  }, 
  { position: "UI Developer", 
    companyName: "Adobe", 
    description: "Required 5 years of experience", 
    applyLink: "https://www.naukri.com/", 
  }, 
  { position: "Program Manager", 
    companyName: "Google", 
    description: "Required 10-12 years of experience", 
    applyLink: "https://www.naukri.com/", 
  }
];
